# Generated by Django 5.2.1 on 2025-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyschedule',
            name='notify_content',
            field=models.CharField(default='no set', max_length=200),
            preserve_default=False,
        ),
    ]
