# Generated by Django 5.2.1 on 2025-05-30 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstExcretionType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'm_excretion_type',
            },
        ),
        migrations.CreateModel(
            name='MstMilkType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'm_milk_type',
            },
        ),
        migrations.CreateModel(
            name='ExcretionRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excretion_records', to='account.child')),
                ('excretion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excretion_records', to='ikujikanri.mstexcretiontype')),
            ],
            options={
                'db_table': 't_excretion_record',
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('left_breast_minutes', models.IntegerField(blank=True, null=True)),
                ('right_breast_minutes', models.IntegerField(blank=True, null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to='account.child')),
                ('milk_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to='ikujikanri.mstmilktype')),
            ],
            options={
                'db_table': 't_milk_record',
            },
        ),
    ]
