# Generated by Django 5.2.1 on 2025-06-05 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItemTemplate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('memo', models.CharField(max_length=200)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_templates', to='account.family')),
                ('shopping_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to='shopping.mstshoppingitemcategory')),
            ],
            options={
                'db_table': 't_shopping_item_template',
            },
        ),
    ]
