# Generated by Django 5.2.1 on 2025-06-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitemtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='shopping_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='shopping.mstshoppingitemcategory'),
        ),
        migrations.AlterField(
            model_name='shoppingitemtemplate',
            name='shopping_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_templates', to='shopping.mstshoppingitemcategory'),
        ),
    ]
